### ISSUE TITLE
PrincipalContext is IDisposable

### ISSUE THREAD

**Issue by kiquenet** [hpcsc/ActiveDirectoryWebApp#2]
About this class:
https://github.com/hpcsc/ActiveDirectoryWebApp/blob/112c3c31f1229a6ff41a50fbad373de1e216bd5a/DirectLDAP/Models/LoginService.cs

**Comment by hpcsc** [comment]
Thanks, never know that it implements IDisposable
Updated the class with using statement in commit 6ae3eac3ac86a4e21e48f8a0a05a2c301ab6b9f2 , just for reference though, haven't had time to test it again
